In [1]:
import sys
sys.path.append('/home/ons21553/wspace/dstools')
from dstools import *

import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

jnt.setup_rcparams()
%matplotlib notebook

946b646783e383ae874abe0cdcfb293669f5fd0edac742c06c76f7caeaf6be91
123


In [2]:
df = pd.read_csv('../data/cleanInfoJune23.csv')
df.columns = [c.lower() for c in df.columns]

In [3]:
df['survey'] = df['id'].apply(lambda x: x.split('_')[0])

In [4]:
df = df[df['type'] != 'matrix_dynamic_cols']
df = df[df['type'] != 'matrix_dynamic_rows']

In [5]:
df.columns

Index(['id', 'type', 'text', 'excl', 'incl', 'duration', 'survey'], dtype='object')

In [6]:
df.head()

id             type  \
0    002_0001_c_1          boolean   
1    002_0001_c_2         dmy_date   
2    002_0001_c_3         dmy_date   
45    002_0001_43          boolean   
48  002_0001_c_45  pound_thousands   

                                                 text excl incl  duration  \
0    Are you able to report for the calendar year ...  NaN  NaN        30   
1    From What are the dates of the 12 month perio...  NaN  NaN        30   
2    To What are the dates of the 12 month period ...  NaN  NaN        30   
45   During the 12 month reporting period    did y...  NaN  NaN        30   
48   Section C   Purchase of R D Conducted Outside...  NaN  NaN        30   

   survey  
0     002  
1     002  
2     002  
45    002  
48    002

In [7]:
df.index = range(len(df))

In [8]:
df.shape

(1457, 7)

In [9]:
df['type'].value_counts()

pound_mills_dec              559
boolean                      168
pound_thousands              148
whole_quant                  140
pound_hunthousands            84
open_text                     62
single_select                 42
dmy_date                      39
pound_mills_dec_balances      38
boolean_2                     24
pound_pence                   12
percentage                    12
FTE                            9
pound_neghunthousands          8
employees                      8
hour_min                       7
pound_mills_dec_purchases      6
contact_2                      6
percentage_dec                 6
open_text_2                    6
signature_date3                5
signature_date2                5
signature_date                 5
contact_5                      4
period                         4
contact_6                      3
contact_4                      3
contact_7                      3
num_years                      2
num_months                     2
contact_10

In [10]:
df['duration'].value_counts()

30    1305
29     118
0       34
Name: duration, dtype: int64

In [11]:
df['survey'].value_counts()

107    520
218    215
009    133
202    111
108     82
120     46
116     43
007     43
062     34
064     34
063     31
065     31
002     27
117     18
169     17
188     17
165     17
210      9
058      9
057      8
068      8
066      4
Name: survey, dtype: int64

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tfidf_vectorizer = TfidfVectorizer(lowercase=True)
tfidf_matrix = tfidf_vectorizer.fit_transform(df['text'])
print(tfidf_matrix.shape)
csm = cosine_similarity(tfidf_matrix, tfidf_matrix)
csm

(1457, 1157)


array([[ 1.        ,  0.49949685,  0.52675765, ...,  0.07510971,
         0.06826382,  0.07449535],
       [ 0.49949685,  1.        ,  0.98289786, ...,  0.05401574,
         0.03310233,  0.03612411],
       [ 0.52675765,  0.98289786,  1.        , ...,  0.068774  ,
         0.03319478,  0.03622499],
       ..., 
       [ 0.07510971,  0.05401574,  0.068774  , ...,  1.        ,
         0.42857687,  0.46769991],
       [ 0.06826382,  0.03310233,  0.03319478, ...,  0.42857687,
         1.        ,  0.90118315],
       [ 0.07449535,  0.03612411,  0.03622499, ...,  0.46769991,
         0.90118315,  1.        ]])

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
sns.set(context="paper", font="monospace")

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(12, 9))

# Draw the heatmap using seaborn
sns.heatmap(csm, vmax=1, square=True)

plt.xticks()
# vst.sparsify_ticks(plt.gca(), every=10)
plt.setp( ax.get_xticklabels(), visible=False)
plt.setp( ax.get_yticklabels(), visible=False)
f.savefig('cosine.png')
;

<IPython.core.display.Javascript object>

''

In [14]:
i = 0
thresh = 0.5

plt.figure(figsize=(12, 5))
sns.distplot((csm > 0.75).sum(axis=1))
plt.figure(figsize=(12, 5))
plt.hist((csm > 0.75).sum(axis=1), bins=20)

<IPython.core.display.Javascript object>

/home/ons21553/apps/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j


<IPython.core.display.Javascript object>

(array([ 485.,  122.,  240.,  102.,   80.,   62.,   26.,    0.,   24.,
           0.,   12.,   60.,   64.,   16.,   88.,    4.,    0.,    0.,
          40.,   32.]),
 array([  1.  ,   4.35,   7.7 ,  11.05,  14.4 ,  17.75,  21.1 ,  24.45,
         27.8 ,  31.15,  34.5 ,  37.85,  41.2 ,  44.55,  47.9 ,  51.25,
         54.6 ,  57.95,  61.3 ,  64.65,  68.  ]),
 <a list of 20 Patch objects>)

In [15]:
df

id             type  \
0       002_0001_c_1          boolean   
1       002_0001_c_2         dmy_date   
2       002_0001_c_3         dmy_date   
3        002_0001_43          boolean   
4      002_0001_c_45  pound_thousands   
5      002_0001_c_46  pound_thousands   
6      002_0001_c_47  pound_thousands   
7      002_0001_c_48  pound_thousands   
8      002_0001_c_d1        employees   
9      002_0001_c_d2        employees   
10     002_0001_c_d3        employees   
11     002_0001_c_d4        employees   
12     002_0001_c_d5        employees   
13     002_0001_c_d6        employees   
14     002_0001_c_d7        employees   
15     002_0001_c_d8        employees   
16     002_0001_c_d9              FTE   
17    002_0001_c_d10              FTE   
18    002_0001_c_d11              FTE   
19    002_0001_c_d12              FTE   
20    002_0001_c_d13              FTE   
21    002_0001_c_d14              FTE   
22    002_0001_c_d15              FTE   
23    002_0001_c_d16              FTE   
24     002_0001_c_e3          boolean   
25     002_0001_c_e4        open_text   
26     002_0001_c_e5        contact_6   
27       007_0003_10          boolean   
28       007_0003_11         dmy_date   
29       007_0003_12         dmy_date   
...              ...              ...   
1427  218_0001_C_357          boolean   
1428  218_0001_C_358      whole_quant   
1429  218_0001_C_359      whole_quant   
1430  218_0001_C_363          boolean   
1431  218_0001_C_375      whole_quant   
1432  218_0001_C_376      whole_quant   
1433  218_0001_C_377      whole_quant   
1434  218_0001_C_374      whole_quant   
1435  218_0001_C_379            hours   
1436  218_0001_C_380          minutes   
1437  218_0001_C_381      pound_pence   
1438  218_0001_C_382      pound_pence   
1439  218_0001_C_378        open_text   
1440    188_0001_c_1        open_text   
1441    188_0001_c_2        open_text   
1442    188_0001_c_3  price_mills_dec   
1443    188_0001_c_4        open_text   
1444    188_0001_c_5        open_text   
1445    188_0001_c_6        open_text   
1446    188_0001_c_7        open_text   
1447    188_0001_c_8          boolean   
1448    188_0001_c_9          boolean   
1449   188_0001_c_10          boolean   
1450   188_0001_c_11        open_text   
1451   188_0001_c_12        open_text   
1452   188_0001_c_13        open_text   
1453   188_0001_c_14        open_text   
1454   188_0001_c_15         hour_min   
1455   188_0001_c_16  pound_mills_dec   
1456   188_0001_c_17  pound_mills_dec   

                                                   text  \
0      Are you able to report for the calendar year ...   
1      From What are the dates of the 12 month perio...   
2      To What are the dates of the 12 month period ...   
3      During the 12 month reporting period    did y...   
4      Section C   Purchase of R D Conducted Outside...   
5      Section C   Purchase of R D Conducted Outside...   
6      Section C   Purchase of R D Conducted Outside...   
7      Section C   Purchase of R D Conducted Outside...   
8      Male researchers On 1 December 2015    how ma...   
9      Female researchers On 1 December 2015    how ...   
10     Male technicians On 1 December 2015    how ma...   
11     Female technicians On 1 December 2015    how ...   
12     Male others On 1 December 2015    how many em...   
13     Female others On 1 December 2015    how many ...   
14     Male On 1 December 2015    what was your tota...   
15     Female On 1 December 2015    what was your to...   
16     Civil researchers During the 12 month reporti...   
17     Defence researchers During the 12 month repor...   
18     Civil technicians During the 12 month reporti...   
19     Defence technicians During the 12 month repor...   
20     Civil others During the 12 month reporting pe...   
21     Defence others During the 12 month reporting ...   
22     Civil During the 12 month reporting period   ...   
23     Defence During the 12 month reporting period ...   


In [17]:
mdf

NameError: name 'mdf' is not defined

In [18]:
def matches(index, smatrix=csm, top=5, thresh=0.5):
    scores = smatrix[index].copy()

    HIGH_VAL = 999
    own_score = scores[index]
    scores[index] = HIGH_VAL

    # put this index on first place
    indices = scores.argsort()[::-1]

    scores.sort()
    scores = scores[::-1]

    comb = list((i, s if s < HIGH_VAL else own_score) for i, s in zip(indices, scores) if s >= thresh)
    if top != None:
        comb = comb[:top]
        
    mdf = df.loc[[i for i, _ in comb]]
    mdf['score'] = [s for _, s in comb]
    return mdf

matches(30)

id       type  \
30  007_0003_201  boolean_2   
31  007_0003_202  boolean_2   
47  007_0003_218  boolean_2   
37  007_0003_208  boolean_2   
35  007_0003_206  boolean_2   

                                                 text excl incl  duration  \
30   Offshore wind  CODE   01 Did the business nam...  NaN  NaN        30   
31   Onshore wind  CODE   02 Did the business name...  NaN  NaN        30   
47   None of the above Did the business named on t...  NaN  NaN        30   
37   Renewable heat  CODE   08 Did the business na...  NaN  NaN        30   
35   Bioenergy  CODE   06 Did the business named o...  NaN  NaN        30   

   survey     score  
30    007  1.000000  
31    007  0.872005  
47    007  0.845555  
37    007  0.839542  
35    007  0.839074

In [23]:
ms = []

for i in range(1000):
    m = matches(i)
    m = m[(m['survey'] != m['survey'][i]) | (m.index == i)]
    m = m[m['score'] > 0.75]
    
    if len(m) > 1:
        ms.append(m)
        
pd.concat(ms).to_csv('examples.csv')

In [20]:
import re
TOKPAT = r"(?u)\b\w\w+\b"
words = re.findall(TOKPAT, df['text'][0].lower())

print(len(words))
print(tfidf_matrix[0, tfidf_matrix[0].nonzero()[1]].getnnz())

29
26


In [ ]:
tfidf_matrix[0].nonzero()

In [ ]:
TfidfVectorizer.t